@extends('admin.layout.forms.add.index')
@section('action' , "about")
@section('title' , trans('language.add'))
@section('page-title',trans('web.about'))
@section('form-groups')
    @includeIf('admin.components.form.add.text', ['label' => trans('language.name_en'),'name'=>'name_en', 'placeholder'=>trans('language.name_en')])
    @includeIf('admin.components.form.add.file', ['label' => trans('language.image'),'name'=>'image', 'max'=>'5'])
    @includeIf('admin.components.form.add.textarea', ['label' => trans('language.des_en'),'name'=>'des_en', 'placeholder'=>trans('language.des_en')])
    @endsection
@section('submit-button-title', trans('web.add'))
